/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { MathUtils } from 'three'

// Higher = snappier crossfade. ~8 lands on roughly a third of a second.
const BLEND_SPEED = 8

export const Developer = ({ animationName="idle", ...props }) => {

  const group = useRef()
  // Only read at mount time, to seed the very first pose without a blend-in.
  const initialAnimation = useRef(animationName)

  const { nodes, materials } = useGLTF('models/developer.glb')

  const { animations: idleAnimation } = useFBX("animations/Idle.fbx") 
  const { animations: saluteAnimation } = useFBX("animations/Salute.fbx") 
  const { animations: cheerAnimation } = useFBX("animations/Cheering.fbx") 
  const { animations: shakeAnimation } = useFBX("animations/Shaking.fbx") 

  idleAnimation[0].name = "idle"
  saluteAnimation[0].name = "salute"
  cheerAnimation[0].name = "cheer"
  shakeAnimation[0].name = "shake"

  const { actions } = useAnimations([idleAnimation[0], saluteAnimation[0], cheerAnimation[0], shakeAnimation[0]], group);

  // Every clip stays playing and is blended purely by weight. Switching mid
  // transition then just re-targets the weights instead of snapping them,
  // which is what fadeIn/fadeOut do (they always ramp from a fixed 0 or 1).
  useEffect(() => {
    Object.entries(actions).forEach(([name, action]) => {
      action.reset();
      action.setEffectiveWeight(name === initialAnimation.current ? 1 : 0);
      action.play();
    });
  }, [actions]);

  useEffect(() => {
    const next = actions[animationName];
    // Rewind the incoming clip only while it is still invisible, so motions
    // like the salute always read from their first frame without popping.
    if (next && next.getEffectiveWeight() < 0.01) {
      next.time = 0;
    }
  }, [animationName, actions]);

  useFrame((_, delta) => {
    Object.entries(actions).forEach(([name, action]) => {
      const target = name === animationName ? 1 : 0;
      const weight = MathUtils.damp(action.getEffectiveWeight(), target, BLEND_SPEED, delta);
      action.setEffectiveWeight(weight < 0.001 ? 0 : weight);
    });
  });

  return (
    <group {...props} dispose={null} ref={group} rotation-x={-Math.PI / 2}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
    </group>
  )
}

useGLTF.preload('models/developer.glb')
